---
title: "filter_join.Rmd"
author: "فؤاد مبارك"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here) 
library(kableExtra)
library(usethis)

```

```{r}

# Read in data

fish <- read_csv(here("data", "fish.csv"))
kelp_abur <- read_excel(here("data", "kelp.xlsx"), sheet = "abur")
```
# user filter function to conditionally subset by rows

```{r}

## filter rows by matching a single character string

fish_garibaldi <- fish %>% 
  filter(common_name == "garibaldi")

## activity
fish_mohk <- fish %>% 
  filter(site == "mohk")
```

# filer rows based on numeric conditions

```{r}
# use the expected operators (>, <, >=, <=, ==)
fish_over50 <- fish %>% 
  filter(total_count >= 50)

```

# filer rows to match this OR that OR that

```{r}

fish_3sp <- fish %>% 
  filter(common_name == "garibaldi" |
           common_name == "blacksmith" |
           common_name == "black sufperch")
# alternatively use the %in% operator if you are looking for multiple matches in the same variable 

fish_3sp <- fish %>% 
  filter(common_name %in% c("garibaldi", "blacksmith", "black surfperch"))

# activity

fish_gar_2016 <- fish %>% 
  filter(year == 2016 | common_name == "garibaldi")

```

# filter to return observations that match this AND that

```{r}
# use comma or AND or & between the arguments

aque_2018 <- fish %>% 
  filter(year == 2018, site == "aque")

aque_2018 <- fish %>% 
  filter(year == 2018 & site == "aque")

# or just do two filer steps in sequence

aque_2018 <- fish %>% 
  filter(year == 2018) %>% 
  filter(site == "aque")


```

# activity: combined filter conditions

```{r}

low_gb_wr <- fish %>% 
  filter(common_name %in% c("garibaldi", "rocK wrasse"),
         total_count <= 10)

low_gb_wr <- fish %>% 
  filter(common_name == "garibaldi" |
           common_name == "rock wrasse" &
         total_count <=10)
```

# filter by a partial pattern

```{r}

fish_bl <- fish %>% 
  filter(str_detect(common_name, pattern = "black"))

# activity

fish_it <- fish %>% 
  filter(str_detect(common_name, pattern = "it"))
```

# merging data frames

```{r}
# full_join to merge dataframes, keeping everything

abur_kelp_fish <- kelp_abur %>% 
  full_join(fish, by = c("year", "site"))

# left_join(x,y) to merge data frames, keeping everything in the x data frame and only matches from the y data frame

kelp_fish_left <- kelp_abur %>% 
  left_join(fish, by = c("year", "site"))

# inner_join to merge data frames, only keeping observations with a match in both

kelp_fish_injoin <- kelp_abur %>% 
  inner_join(fish, by = c("year", "site"))


# filter and join in a sequence

my_fish_join <- fish %>% 
  filter(year == 2017, site == "Arroyo Burro") %>% 
  left_join(kelp_abur, by = c("year", "site")) %>% 
  mutate(fish_per_frond = total_count/total_fronds)
```

