---
title: "Creating graphs in R with ggplot2"
author: "فؤاد مبارك"
date: "2023-01-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(here)
library(usethis)

## use_git_config function with my username and email to connect to GitHub 

use_git_config(user.name ="fuadalzahrani", user.email = "fuadalzahrani87@gmail.com")
```


```{r read in files}
ca_np <- read_csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

# Our first plot
```{r}
ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line() 

# store the first line as gg_base so we do not retype it each time

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))

# change it to a scatterplot

gg_base +
  geom_point()

# column graph
gg_base +
  geom_col()

# area plot
gg_base +
  geom_area()
```

# customizing plots

```{r}
gg_base +
  geom_line(
    colour = "purple",
    linetype = "dashed"
  ) 

gg_base +
  geom_point(colour = "purple",
             pch = 17,
             size = 4, 
             alpha = 0.5)
```
## Mapping variables into aesthetics

```{r}
gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    alpha = 0.5
  )

gg_base +
  geom_col(
    aes(fill = visitors),
    alpha = 0.5
  )
```

